### ISSUE TITLE
DigiKeyboard

### ISSUE THREAD

**Issue by Cmd-Monkey** [Gadotti/DigisparkScripts#1]
Olá, cara parabéns pelo seus códigos, são bem legais, mas tenho uma duvida quanto a biblioteca DigiKeyboard que você criou, esses dias eu estava tentando criar uma também ([aqui](https://github.com/Cmd-Monkey/DigisparkKeyboard)) mas não importa oque eu faça algumas teclas como o ç e alguns acentos não funcionam, usando a sua biblioteca também não funcionou, isso é só no meu pc ou ocorre em todos?

eu estava rodando esse script como teste:
` DigiKeyboard.delay(1000);`
  `DigiKeyboard.println("ABCDEFGHIJKLMNOPQRSTUVWXYZ");`
 ` DigiKeyboard.println("abcdefghijklmnopqrstuvwxyz");`
  `DigiKeyboard.println("1234567890");`
  `DigiKeyboard.println("!@#$%&*()_+=-");`
`  DigiKeyboard.println("[]{}\\|;:',./<>?");`
`  DigiKeyboard.println("ççÇÇ"); `

o output com a sua biblioteca ficou:

> ABCDEFGHIJKLMNOPQRSTUVWXYZ
abcdefghijklmnopqrstuvwxyz
1234567890
!@#$%&*()_+=-
´[`{]}çÇ~,.;<>:
gggvgv

o output com a minha biblioteca ficou:

> ABCDEFGHIJKLMNOPQRSTUVWXYZ
abcdefghijklmnopqrstuvwxyz
1234567890
!@#$%&*()_+=-
[]{}\\|;:',./<>?
gggvgv

você acha que de alguma forma tem como fazer isso funcionar? Eu sou meio leigo no assunto.
Obrigado.

**Comment by Gadotti** [comment]
Olá **Cmd-Monkey!**

Fiquei muito feliz com a sua issue e saber que há pessoas utilizando de alguma forma.
Você me ajudou a melhorar a biblioteca demonstrando este problema.

Eu atualiziei o arquivo **DigiKeyboardPtBr.h** dos meus scripts com uma nova versão que imprime corretamente o seu texto teste. Só não consegui mapear o 'Ç', que está imprimindo 'ç' (minúsculo).

Eu notei que a biblioteca base que você utiliza está mais distante do mapeamento correto, ele utiliza o método no write:
`uint8_t data = pgm_read_byte_near(ascii_to_scan_code_table + (chr - 8));
 sendKeyStroke(data & 0b01111111, data >> 7 ? MOD_SHIFT_RIGHT : 0 | (data << 1) >> 7 ? MOD_ALT_RIGHT : 0);`

Recomendo atualizar com a biblioteca que fiz upload.

Dei uma olhada na biblioteca que está no seu repositório e ela me deu a ideia para resolver o problema do 'ç'. O array de caracteres que é feito o mapeamento é só até 128 bytes (posições) e o 'ç' era o byte 195, então fiz um patch verificando o código do caractere:
`if (chr == 195) {
          sendKeyStroke(0x33); 
          //sendKeyStroke(0x33, MOD_SHIFT_LEFT);
        }`

Outros caracteres como o '?' ou '\' que também não estava corretos na minha biblioteca, atualizei o mapeamento dentro do array padrão mesmo.

Agradeço pela issue e qualquer coisa é só mandar outra mensagem.

**Comment by Cmd-Monkey** [comment]
Cara, parabéns pelo seu código, ficou perfeito, rodei vários códigos e todos rodaram sem problemas, em questão sobre o ç, eu acabei "percebendo" que o char 195 é pra qualquer carácter especial, então ao usar qualquer assento  ele acaba printando ç, mas pelo que eu pesquisei pra conseguir o Ç e os assentos é algo muito complexo (eu sou bem noob nisso) e, sinceramente, desnecessário.
Mas uma vez, muito obrigado pela biblioteca, salvou vários códigos :)
